### ISSUE TITLE
Retreive current layout from board.

### ISSUE THREAD

**Issue by KenwoodFox** [SonicRift/Vestaboard#16]
Id like to be able to save the text currently displayed on the board.

Im wondering if there is a way to collect and return the data (perhaps in the same format as raw)

Ive checked through the docs, im not sure if theres a way to read back the displayed text. Is there?

**Comment by SonicRift** [comment]
Hi @KenwoodFox!
Sorry to say there is no way to do that. Since installables could potentially be pushing sensitive/personal information to a given board (think calendar for the day, or a personal private message to a loved one), you cannot retrieve information from the board; it's a one-way street.
I do know, though, that the Vestaboard team was looking into adding a way to retrieve a message ID, though, which may help depending on your use case.
Essentially you would get back a message ID as a confirmation when pushing a message to the board, then you could check the currently-displayed message ID, and if they match then the board is still displaying the message you just sent, otherwise either the user has changed it or another installable has sent a message overriding yours.
Hope that helps!

- Shane

**Comment by KenwoodFox** [comment]
That's unfortunate but understandable~ I was hoping that a user could input a custom layout/string into the webgui, and then save it into a list to repeat later at specific times using a custom installable. Ill work around the limitation though, thanks for your response.
